name: viary
description: Voice Diary

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0

  speech_to_text: ^6.1.0

  intl: ^0.17.0
  qr_flutter: ^4.0.0
  json_serializable: ^6.1.4
  google_fonts: ^3.0.1

  domain:
    path: ../domain
  freezed: ^2.2.1
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
