name: "[iOS] Build and Test App"

on:
  push:
    branches:
      - dev
      - main
  pull_request:

defaults:
  run:
    working-directory: ./

jobs:
  test:
    name: "Build iOSApp"
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: "Install xcbeautify"
        run: brew install xcbeautify
      - name: "Build and Test"
        working-directory: ios-dev
        run: |
          set -o pipefail
          xcodebuild CI=YES -project ios-dev.xcodeproj -scheme ios-dev build -destination 'platform=iOS Simulator,name=iPhone 14' | xcbeautify
