name: "[iOS] Build and Test App"

on:
  push:
    branches:
      - dev
      - main
  pull_request:

defaults:
  run:
    working-directory: ./

jobs:
  test:
    name: "Build iOSApp"
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: "Install xcbeautify"
        run: brew install xcbeautify
      - name: Install mint
        run: brew install mint
      - name: "Test Sources"
        run: |
          set -e
          set -o pipefail
          xcodebuild -scheme Viary test -destination "name=iPhone 14" | xcbeautify
      - name: "Build dev project"
        working-directory: ios-dev
        run: |
          set -e
          set -o pipefail
          xcodebuild -project ios-dev.xcodeproj -scheme ios-dev build test -destination 'platform=iOS Simulator,name=iPhone 14' "OTHER_SWIFT_FLAGS=-D CI" | xcbeautify
