name: "[iOS] Build and Test App"

on:
  push:
    branches:
      - dev
      - main
  pull_request:

defaults:
  run:
    working-directory: ./ios

jobs:
  test:
    name: "Build iOSApp"
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable            
      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild -project ios.xcodeproj -scheme ios build -destination 'platform=iOS Simulator,name=iPhone 13' | bundle exec xcpretty
